# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_id', to='app.Profile'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_id', to='app.Profile'),
        ),
    ]
